# profiles.yml

dbt_sf_project:
  outputs:
    dev:
      account: XYPHKVE.WD62074.aws
      database: PC_DBT_DB
      password: flia12696ERQ
      role: accountadmin
      schema: DBT_SMURUA
      threads: 1
      type: snowflake
      user: fliamuruacbabkp
      warehouse: compute_wh
  target: dev