name: change_file_location

on: 
    push:
        branches: [main]

jobs:
    move_file_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: Move file
              run: |
                mv models/staging/*.sql executed_models/staging/
            
            - name: Commit changes
              run: |
                git config --local user.email "muruasimon@gmail.com"
                git config --local user.name "muruasimon"
                git add .
                git commit -m "Move SQL files from source folder to destination folder"

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}